FROM python:3.13.2-alpine3.21

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install --default-timeout=300 -r requirements.txt

EXPOSE 8000

CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]