# Generated by Django 5.1.4 on 2025-01-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_accounts_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='profile_img_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
