# Generated by Django 5.1.5 on 2025-02-17 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20250217_0350'),
    ]

    operations = [
    ]
