# Generated by Django 5.1.5 on 2025-02-17 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20250217_0351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='email',
            new_name='username',
        ),
    ]
