# Generated by Django 5.1.5 on 2025-02-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_accounts_options_alter_accounts_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='username',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
