# Generated by Django 5.1.5 on 2025-02-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_accounts_email_alter_accounts_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
